export const HOME = 'home';
export const LOGIN = 'login';
export const PROFILE = 'profile';
export const HELP = 'help';
// export const TIMER = 'timer';
export const NEW_PROJECT = 'newProject';
export const EDIT_PROJECT = 'editProject';
export const PROJECT_DATA = 'projectData';
export const TEST_SCREEN = 'testScreen';
